### PR TITLE
Add fetching data from Gravez.me

### PR DESCRIPTION
**Pull request by GuyKh**

### CODE REVIEW

**Comment by GuyKh** [comment]
Don't merge yet. Need to verify it's working

**Comment by GuyKh** [comment]
Checked and Verified

**Comment by jeffg2k** [comment]
Thank you for this and the Hebrew translation.  I'm going to do a little work on the date to make sure it formats properly.  It appears the site uses d/m/yyyy, so we'll want to make sure it reads that and not m/d/yyyy.  After that, I'll do a version bump and push it out.

**Comment by jeffg2k** [comment]
As a side thought, you may want to consider changing the date formatting to something that is not ambiguous.  Many genealogical errors have been made by unknowingly transposing the month and day.  If you want to use numerical values, a international standard format of yyyy-mm-dd would probably be better, as the US tends to use mm/dd/yyyy and others dd/mm/yyyy.  But I'd suggest just spelling out the month either fully or abbreviated, 4 Sep 1943.  No ambiguity

**Comment by jeffg2k** [comment]
Sorry, I thought you were the requester from this post https://github.com/jeffg2k/SmartCopy/issues/94 who ran the sites.  If you do happen to have any influence on gravez.me, then maybe that will be helpful, otherwise disregard. :)

**Pull request merged**
