### PR TITLE
Geneanet: Do not select tags with images

### PR DESCRIPTION
**Pull request by raphink**
On some pages, people names are prepended with a SOSA link.
The only way to detect this SOSA link is that it contains an images
(with an alt="sosa" tag).

### CODE REVIEW

**Comment by jeffg2k** [comment]
Weird - I thought we stripped out all img tags when we build the jquery object to prevent it from wasting time and bandwidth downloading images.  Do you have an example page - I'd like to see what is going on.

**Comment by raphink** [comment]
No I don't think we did for this collection, because we need images to determine gender.

**Comment by raphink** [comment]
And it's a good thing we didn't, otherwise there'd be no way to exclude these A sosa tags.

**Comment by raphink** [comment]
Btw, whenever you're thinking of cutting a release, I'll be happy to announce it on French groups in geni. It might very well increase geni adoption here, considering the sheer amount of French data on geneanet.

**Comment by jeffg2k** [comment]
We can do both.. just replace the IMG tab with a GMI tag, then jquery gmi.  That way you can find it, without having to download the pictures.

**Comment by jeffg2k** [comment]
Switched it to GMI to hopefully deal with both situations https://github.com/jeffg2k/SmartCopy/commit/49cd0d8fbb35526fec953a1f7a4c52a55389bedb
Wish there was an option in jquery to tell it not to download the images as it processes the code.

**Comment by raphink** [comment]
Is there no way to query directly the DOM of the tab instead of "replaying" it from source ?

**Comment by jeffg2k** [comment]
That would only be applicable to the focus if reload = false, otherwise the focus and relatives are queried via XHR.

**Comment by raphink** [comment]
Ah yes, there's the relatives anyway indeed...

**Pull request merged**
